# Generated by Django 5.2.7 on 2025-10-30 21:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('course_material', 'Course Material'), ('assignment_submission', 'Assignment Submission'), ('certificate', 'Certificate'), ('user_avatar', 'User Avatar'), ('course_thumbnail', 'Course Thumbnail'), ('recording', 'Class Recording'), ('document', 'Document'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('allowed_extensions', models.JSONField(default=list)),
                ('max_file_size_mb', models.PositiveIntegerField(default=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'File Categories',
                'db_table': 'file_categories',
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('file_size', models.PositiveIntegerField()),
                ('file_type', models.CharField(max_length=100)),
                ('file_extension', models.CharField(max_length=10)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('tenant', 'Tenant Only'), ('enrolled', 'Enrolled Students Only'), ('instructor', 'Instructor Only'), ('private', 'Private')], default='private', max_length=20)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='uploading', max_length=20)),
                ('processing_status', models.JSONField(blank=True, default=dict)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='accessible_files', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='files.filecategory')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.course')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.organization')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('thumbnail', 'Generate Thumbnail'), ('video_transcode', 'Video Transcoding'), ('document_preview', 'Document Preview'), ('virus_scan', 'Virus Scan'), ('metadata_extraction', 'Metadata Extraction')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.organization')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='files.fileupload')),
            ],
            options={
                'db_table': 'file_processing_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='files.fileupload')),
            ],
            options={
                'db_table': 'file_access_logs',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['category', 'status'], name='file_upload_categor_8ed850_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='file_upload_uploade_bfd22c_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['course', 'access_level'], name='file_upload_course__2b4d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='fileprocessingjob',
            index=models.Index(fields=['file', 'job_type'], name='file_proces_file_id_122744_idx'),
        ),
        migrations.AddIndex(
            model_name='fileprocessingjob',
            index=models.Index(fields=['status', 'created_at'], name='file_proces_status_9d7d22_idx'),
        ),
        migrations.AddIndex(
            model_name='fileaccesslog',
            index=models.Index(fields=['file', 'accessed_at'], name='file_access_file_id_57ead1_idx'),
        ),
        migrations.AddIndex(
            model_name='fileaccesslog',
            index=models.Index(fields=['user', 'accessed_at'], name='file_access_user_id_dac85f_idx'),
        ),
    ]
