# Generated by Django 5.2.7 on 2025-11-08 21:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('instructions', models.TextField(blank=True)),
                ('assignment_type', models.CharField(choices=[('essay', 'Essay'), ('project', 'Project'), ('quiz', 'Quiz'), ('presentation', 'Presentation'), ('code', 'Code Assignment'), ('other', 'Other')], default='essay', max_length=20)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('passing_score', models.PositiveIntegerField(default=60)),
                ('allow_file_upload', models.BooleanField(default=True)),
                ('max_file_size_mb', models.PositiveIntegerField(default=10)),
                ('allowed_file_types', models.JSONField(blank=True, default=list)),
                ('due_date', models.DateTimeField()),
                ('late_submission_allowed', models.BooleanField(default=True)),
                ('late_penalty_percent', models.PositiveIntegerField(default=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('weight_percentage', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assignments',
                'ordering': ['due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_type', models.CharField(choices=[('completion', 'Certificate of Completion'), ('achievement', 'Certificate of Achievement'), ('participation', 'Certificate of Participation'), ('excellence', 'Certificate of Excellence')], default='completion', max_length=20)),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('completion_date', models.DateTimeField()),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='certificate_qr_codes/')),
                ('verification_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'certificates',
                'ordering': ['-issued_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modules_completed', models.JSONField(default=list)),
                ('assignments_completed', models.JSONField(default=list)),
                ('live_classes_attended', models.JSONField(default=list)),
                ('overall_progress_percentage', models.PositiveIntegerField(default=0)),
                ('assignment_average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_requirements_met', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'course_progress',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_content', models.TextField(blank=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('is_graded', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('late', 'Late Submission'), ('graded', 'Graded'), ('returned', 'Returned for Revision')], default='draft', max_length=20)),
                ('is_late', models.BooleanField(default=False)),
                ('late_penalty_applied', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'submissions',
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
    ]
