# Generated by Django 5.2.7 on 2025-11-08 21:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('course_enrollment', 'Course Enrollment'), ('class_reminder', 'Class Reminder'), ('assignment_due', 'Assignment Due'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('payment_overdue', 'Payment Overdue'), ('subscription_renewed', 'Subscription Renewed'), ('subscription_cancelled', 'Subscription Cancelled'), ('invoice_sent', 'Invoice Sent'), ('teacher_approval', 'Teacher Approval'), ('system', 'System')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_email', models.BooleanField(default=False)),
                ('sent_push', models.BooleanField(default=False)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailDeliveryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('template_used', models.CharField(blank=True, max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.organization')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='notifications.notification')),
            ],
            options={
                'db_table': 'email_delivery_logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['room_name', '-created_at'], name='chat_messag_room_na_5d23a2_idx'), models.Index(fields=['user', '-created_at'], name='chat_messag_user_id_790302_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('notification_type', models.CharField(choices=[('course_enrollment', 'Course Enrollment'), ('class_reminder', 'Class Reminder'), ('assignment_due', 'Assignment Due'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('payment_overdue', 'Payment Overdue'), ('subscription_renewed', 'Subscription Renewed'), ('subscription_cancelled', 'Subscription Cancelled'), ('invoice_sent', 'Invoice Sent'), ('teacher_approval', 'Teacher Approval'), ('system', 'System')], max_length=50)),
                ('subject_template', models.CharField(max_length=255)),
                ('html_template', models.TextField()),
                ('text_template', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.organization')),
            ],
            options={
                'db_table': 'notification_templates',
                'unique_together': {('tenant', 'notification_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WebSocketConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connection_type', models.CharField(choices=[('notifications', 'Notifications'), ('chat', 'Chat'), ('live_class', 'Live Class')], max_length=50)),
                ('channel_name', models.CharField(max_length=255)),
                ('room_name', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websocket_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'websocket_connections',
                'ordering': ['-connected_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='websocket_c_user_id_0bac24_idx'), models.Index(fields=['connection_type', 'is_active'], name='websocket_c_connect_dd90a8_idx')],
            },
        ),
    ]
