# Generated by Django 4.2.7 on 2025-10-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('course_enrollment', 'Course Enrollment'), ('class_reminder', 'Class Reminder'), ('assignment_due', 'Assignment Due'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('payment_overdue', 'Payment Overdue'), ('subscription_renewed', 'Subscription Renewed'), ('subscription_cancelled', 'Subscription Cancelled'), ('invoice_sent', 'Invoice Sent'), ('teacher_approval', 'Teacher Approval'), ('system', 'System')], max_length=50),
        ),
    ]
