# Generated by Django 4.2.7 on 2025-10-19 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_userprofile_role_alter_userprofile_user'),
        ('admin_tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('overview', 'Overview Report'), ('enrollment', 'Enrollment Report'), ('financial', 'Financial Report'), ('course', 'Course Performance Report')], max_length=20)),
                ('format_type', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('pdf', 'PDF')], default='pdf', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
                ('execute_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='scheduled', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('download_url', models.URLField(blank=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_completion', models.DateTimeField(blank=True, null=True)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.organization')),
            ],
            options={
                'db_table': 'scheduled_reports',
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['created_by', 'scheduled_at'], name='scheduled_r_created_a1b99b_idx'), models.Index(fields=['status', 'scheduled_at'], name='scheduled_r_status_b03423_idx'), models.Index(fields=['report_type', 'scheduled_at'], name='scheduled_r_report__92e019_idx')],
            },
        ),
    ]
