# Generated by Django 4.2.7 on 2025-10-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tools', '0002_scheduledreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_logs_user_id_88267f_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_logs_object__c88dfc_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_logs_action_474804_idx',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='changes',
            new_name='new_values',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='object_type',
            new_name='resource_type',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='object_repr',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='old_values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='resource_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('read', 'Read'), ('login', 'Login'), ('logout', 'Logout'), ('payment', 'Payment'), ('enrollment', 'Enrollment'), ('error', 'Error'), ('maintenance', 'Maintenance'), ('bulk_operation', 'Bulk Operation'), ('export', 'Export')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='audit_logs_user_id_fbfd51_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type', 'created_at'], name='audit_logs_resourc_b47635_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='audit_logs_action_391715_idx'),
        ),
    ]
