# Generated by Django 5.2.7 on 2025-11-08 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['status', 'publish_at'], name='content_ann_status_7aa28a_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['category', 'status'], name='content_ann_categor_4b68ea_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['featured', 'show_on_homepage'], name='content_ann_feature_7ed74f_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['status', 'category'], name='content_faq_status_d48a12_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['featured', 'status'], name='content_faq_feature_08d250_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['category', 'display_order'], name='content_faq_categor_8620c9_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['status', 'featured'], name='content_tea_status_c2f9bb_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['department', 'display_order'], name='content_tea_departm_b985ad_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['status', 'featured'], name='content_tes_status_259352_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['created_at'], name='content_tes_created_4b2c30_idx'),
        ),
    ]
