# Generated by Django 5.2.7 on 2025-10-30 21:50

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIContentSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('live_class', 'Live Class Recording'), ('course_module', 'Course Module'), ('video', 'Video Content'), ('text', 'Text Content')], max_length=20)),
                ('content_id', models.UUIDField()),
                ('content_title', models.CharField(max_length=200)),
                ('original_content', models.TextField()),
                ('summary', models.TextField()),
                ('key_points', models.JSONField(default=list)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('generation_time_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_content_summaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('conversation_type', models.CharField(choices=[('tutor', 'AI Tutor Chat'), ('general', 'General Chat'), ('course_help', 'Course Help')], default='tutor', max_length=20)),
                ('context', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_conversations',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIQuiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('source_content', models.TextField()),
                ('questions', models.JSONField(default=list)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('generation_time_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRateLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requests_per_minute', models.PositiveIntegerField(default=10)),
                ('requests_per_hour', models.PositiveIntegerField(default=100)),
                ('requests_per_day', models.PositiveIntegerField(default=500)),
                ('minute_window_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('minute_requests', models.PositiveIntegerField(default=0)),
                ('hour_window_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('hour_requests', models.PositiveIntegerField(default=0)),
                ('day_window_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('day_requests', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_rate_limits',
            },
        ),
        migrations.CreateModel(
            name='AIUsageQuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('chat_messages_used', models.PositiveIntegerField(default=0)),
                ('chat_messages_limit', models.PositiveIntegerField(default=100)),
                ('chat_tokens_used', models.PositiveIntegerField(default=0)),
                ('chat_tokens_limit', models.PositiveIntegerField(default=50000)),
                ('summaries_generated', models.PositiveIntegerField(default=0)),
                ('summaries_limit', models.PositiveIntegerField(default=20)),
                ('summary_tokens_used', models.PositiveIntegerField(default=0)),
                ('summary_tokens_limit', models.PositiveIntegerField(default=100000)),
                ('quizzes_generated', models.PositiveIntegerField(default=0)),
                ('quizzes_limit', models.PositiveIntegerField(default=10)),
                ('quiz_tokens_used', models.PositiveIntegerField(default=0)),
                ('quiz_tokens_limit', models.PositiveIntegerField(default=50000)),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('cost_limit_usd', models.DecimalField(decimal_places=4, default=10.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_usage_quotas',
            },
        ),
    ]
