# Generated by Django 5.2.7 on 2025-10-30 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ai', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aicontentsummary',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summaries', to='courses.course'),
        ),
        migrations.AddField(
            model_name='aicontentsummary',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='aicontentsummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='courses.course'),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.aiconversation'),
        ),
        migrations.AddField(
            model_name='aiquiz',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_quizzes', to='courses.course'),
        ),
        migrations.AddField(
            model_name='aiquiz',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='aiquiz',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='airatelimit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_rate_limits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiusagequota',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='aiusagequota',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='airatelimit',
            unique_together={('user',)},
        ),
        migrations.AlterUniqueTogether(
            name='aiusagequota',
            unique_together={('user', 'month', 'tenant')},
        ),
    ]
