# Generated by Django 4.2.7 on 2025-10-09 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_userprofile_role_alter_userprofile_user'),
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiconversation',
            options={'ordering': ['-last_activity']},
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='conversation_type',
            field=models.CharField(choices=[('tutor', 'AI Tutor Chat'), ('general', 'General Chat'), ('course_help', 'Course Help')], default='tutor', max_length=20),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='courses.course'),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='response_time_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='tokens_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiusagequota',
            name='chat_tokens_limit',
            field=models.PositiveIntegerField(default=50000),
        ),
        migrations.AddField(
            model_name='aiusagequota',
            name='chat_tokens_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiusagequota',
            name='cost_limit_usd',
            field=models.DecimalField(decimal_places=4, default=10.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='aiusagequota',
            name='quiz_tokens_limit',
            field=models.PositiveIntegerField(default=50000),
        ),
        migrations.AddField(
            model_name='aiusagequota',
            name='quiz_tokens_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiusagequota',
            name='summary_tokens_limit',
            field=models.PositiveIntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='aiusagequota',
            name='summary_tokens_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiusagequota',
            name='total_cost_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='AIQuiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('source_content', models.TextField()),
                ('questions', models.JSONField(default=list)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('generation_time_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_quizzes', to='courses.course')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIContentSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('live_class', 'Live Class Recording'), ('course_module', 'Course Module'), ('video', 'Video Content'), ('text', 'Text Content')], max_length=20)),
                ('content_id', models.UUIDField()),
                ('content_title', models.CharField(max_length=200)),
                ('original_content', models.TextField()),
                ('summary', models.TextField()),
                ('key_points', models.JSONField(default=list)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('generation_time_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summaries', to='courses.course')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_content_summaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRateLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requests_per_minute', models.PositiveIntegerField(default=10)),
                ('requests_per_hour', models.PositiveIntegerField(default=100)),
                ('requests_per_day', models.PositiveIntegerField(default=500)),
                ('minute_window_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('minute_requests', models.PositiveIntegerField(default=0)),
                ('hour_window_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('hour_requests', models.PositiveIntegerField(default=0)),
                ('day_window_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('day_requests', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_rate_limits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_rate_limits',
                'unique_together': {('user',)},
            },
        ),
    ]
