# Generated by Django 5.2.7 on 2025-11-08 21:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('recording_type', models.CharField(choices=[('zoom_cloud', 'Zoom Cloud Recording'), ('zoom_local', 'Zoom Local Recording'), ('manual_upload', 'Manual Upload'), ('processed', 'Processed Recording')], default='zoom_cloud', max_length=20)),
                ('file_url', models.URLField()),
                ('file_size_mb', models.PositiveIntegerField(default=0)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('file_format', models.CharField(default='mp4', max_length=10)),
                ('access_level', models.CharField(choices=[('enrolled', 'Enrolled Students Only'), ('public', 'Public Access'), ('instructor', 'Instructor Only'), ('premium', 'Premium Students Only')], default='enrolled', max_length=20)),
                ('password_protected', models.BooleanField(default=False)),
                ('access_password', models.CharField(blank=True, max_length=100)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_status', models.CharField(default='pending', max_length=50)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('recorded_at', models.DateTimeField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'class_recordings',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="CSS icon class (e.g., 'fas fa-laptop-code')", max_length=50)),
                ('color', models.CharField(blank=True, help_text="Hex color code (e.g., '#3B82F6')", max_length=7)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Course Categories',
                'db_table': 'course_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CourseLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_type', models.CharField(choices=[('standard', 'Standard License'), ('extended', 'Extended License'), ('commercial', 'Commercial License'), ('educational', 'Educational License')], default='standard', max_length=20)),
                ('terms', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'course_licenses',
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('video_url', models.URLField(blank=True)),
                ('materials', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'course_modules',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'course_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'enrollments',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('zoom_meeting_id', models.CharField(blank=True, max_length=100)),
                ('join_url', models.URLField(blank=True)),
                ('start_url', models.URLField(blank=True)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('recording_url', models.URLField(blank=True)),
                ('recording_password', models.CharField(blank=True, max_length=50)),
                ('has_recording', models.BooleanField(default=False)),
                ('recording_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'live_classes',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('view', 'Viewed Recommendation'), ('click', 'Clicked on Course'), ('wishlist', 'Added to Wishlist'), ('enroll', 'Enrolled in Course'), ('dismiss', 'Dismissed Recommendation')], max_length=20)),
                ('algorithm_used', models.CharField(blank=True, choices=[('collaborative', 'Collaborative Filtering'), ('content_based', 'Content-Based Filtering'), ('popularity', 'Popularity-Based'), ('hybrid', 'Hybrid Algorithm'), ('wishlist_based', 'Wishlist-Based')], max_length=20, null=True)),
                ('recommendation_score', models.FloatField(blank=True, null=True)),
                ('recommendation_reason', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('page_context', models.CharField(blank=True, max_length=100)),
                ('position_in_list', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recommendation_interactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this course')),
                ('notify_price_change', models.BooleanField(default=True)),
                ('notify_course_updates', models.BooleanField(default=True)),
                ('notify_enrollment_opening', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wishlists',
                'ordering': ['-priority', '-added_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('max_students', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_weeks', models.PositiveIntegerField(default=4)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.organization')),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
    ]
