# Generated by Django 4.2.7 on 2025-10-13 22:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='has_recording',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='recording_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ClassRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('recording_type', models.CharField(choices=[('zoom_cloud', 'Zoom Cloud Recording'), ('zoom_local', 'Zoom Local Recording'), ('manual_upload', 'Manual Upload'), ('processed', 'Processed Recording')], default='zoom_cloud', max_length=20)),
                ('file_url', models.URLField()),
                ('file_size_mb', models.PositiveIntegerField(default=0)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('file_format', models.CharField(default='mp4', max_length=10)),
                ('access_level', models.CharField(choices=[('enrolled', 'Enrolled Students Only'), ('public', 'Public Access'), ('instructor', 'Instructor Only'), ('premium', 'Premium Students Only')], default='enrolled', max_length=20)),
                ('password_protected', models.BooleanField(default=False)),
                ('access_password', models.CharField(blank=True, max_length=100)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_status', models.CharField(default='pending', max_length=50)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('recorded_at', models.DateTimeField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='courses.liveclass')),
            ],
            options={
                'db_table': 'class_recordings',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
