# Generated by Django 4.2.7 on 2025-10-13 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_populate_file_categories'),
        ('courses', '0002_liveclass_has_recording_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_thumbnails', to='files.fileupload'),
        ),
    ]
