# Generated by Django 4.2.7 on 2025-10-16 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_userprofile_role_alter_userprofile_user'),
        ('courses', '0004_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('view', 'Viewed Recommendation'), ('click', 'Clicked on Course'), ('wishlist', 'Added to Wishlist'), ('enroll', 'Enrolled in Course'), ('dismiss', 'Dismissed Recommendation')], max_length=20)),
                ('algorithm_used', models.CharField(blank=True, choices=[('collaborative', 'Collaborative Filtering'), ('content_based', 'Content-Based Filtering'), ('popularity', 'Popularity-Based'), ('hybrid', 'Hybrid Algorithm'), ('wishlist_based', 'Wishlist-Based')], max_length=20, null=True)),
                ('recommendation_score', models.FloatField(blank=True, null=True)),
                ('recommendation_reason', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('page_context', models.CharField(blank=True, max_length=100)),
                ('position_in_list', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_interactions', to='courses.course')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendation_interactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='recommendat_user_id_6c88df_idx'), models.Index(fields=['course', 'interaction_type'], name='recommendat_course__922105_idx'), models.Index(fields=['algorithm_used', 'created_at'], name='recommendat_algorit_352f48_idx')],
            },
        ),
    ]
