# Generated by Django 4.2.7 on 2025-10-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_populate_subscription_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_file_size_mb',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='monthly_download_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='premium_content_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='recording_access',
            field=models.BooleanField(default=False),
        ),
    ]
